language: cpp
dist: bionic

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - sudo apt-get install -y qt5-default cmake

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE:STRING=${BUILD_TYPE} ..
  - make -j2

after_failure:
  - cat qsqlmigrator-prefix/src/qsqlmigrator-stamp/qsqlmigrator-build-*.log
