language: cpp
compiler: gcc
dist: bionic

install:
  - sudo apt-get install -y qt5-default cmake

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2

after_failure:
  - cat qsqlmigrator-prefix/src/qsqlmigrator-stamp/qsqlmigrator-build-*.log
